### ISSUE TITLE
Typo in Subscribe method

### ISSUE THREAD

**Issue by FZambia** [synw/centcom#1]
Noticed a typo in `Subscribe` method - it's now called [Suscribe](https://github.com/synw/centcom/blob/master/ws.go#L48). The same for `Unsubscribe`

**Comment by synw** [comment]
Thanks for reporting it. I will fix.

**Comment by synw** [comment]
Fixed: https://github.com/synw/centcom/commit/a125105d3428cced2e03d771d5ef7392dcc5e805
